/*  GIMP header image file format (RGB): /home/bas/Dokumentoj/Uberprachtige-KBS-game/Sprites/blokje.h  */

static unsigned int width = 16;
static unsigned int height = 16;

/*  Call this macro repeatedly.  After each use, the pixel data can be extracted  */

#define HEADER_PIXEL(data,pixel) {\
pixel[0] = (((data[0] - 33) << 2) | ((data[1] - 33) >> 4)); \
pixel[1] = ((((data[1] - 33) & 0xF) << 4) | ((data[2] - 33) >> 2)); \
pixel[2] = ((((data[2] - 33) & 0x3) << 6) | ((data[3] - 33))); \
data += 4; \
}
static char *header_data =
	"1E)S;WN2;WN2;WN2;WN2;WN2;WN2;WN2;WN2;WN2;WN2;WN2;WN2;WN2;WN21E)S"
	";WN2IZJMIJFLIJFLIJFLIJFLIJFLIJFLIJFLIJFLIJFLIJFLIJFLIJFLHZ:H34Y?"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2IJFLIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJIJBJHZ2F2DI9"
	";WN2HZ:HHZ2FHZ2FHZ2FHZ2FHZ2FHZ2FHZ2FHZ2FHZ2FHZ2FHZ2FHZ2FH*&C2DI9"
	"1E)S34Y?2DI92DI92DI92DI92DI92DI92DI92DI92DI92DI92DI92DI92DI9+C-."
	"";
